"""enterprise_upgrades

Revision ID: 9ae0bf8004b0
Revises: b4e621340e1e
Create Date: 2026-07-01 11:22:07.500767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae0bf8004b0'
down_revision: Union[str, None] = 'b4e621340e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_categories', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('assets', sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('purchase_cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('warranty_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('purchase_notes', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('photos', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('assets', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('condition', sa.String(length=40), nullable=False, server_default='Good'))
    op.add_column('borrow_transactions', sa.Column('condition_out', sa.String(length=40), nullable=True))
    op.add_column('borrow_transactions', sa.Column('condition_in', sa.String(length=40), nullable=True))
    op.add_column('borrow_transactions', sa.Column('condition_alert', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('borrow_transactions', 'initial_condition')
    op.drop_column('borrow_transactions', 'return_condition')
    op.add_column('locations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_active')
    op.drop_column('locations', 'is_active')
    op.add_column('borrow_transactions', sa.Column('return_condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('borrow_transactions', sa.Column('initial_condition', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('borrow_transactions', 'condition_alert')
    op.drop_column('borrow_transactions', 'condition_in')
    op.drop_column('borrow_transactions', 'condition_out')
    op.drop_column('assets', 'condition')
    op.drop_column('assets', 'notes')
    op.drop_column('assets', 'photos')
    op.drop_column('assets', 'purchase_notes')
    op.drop_column('assets', 'warranty_expiry')
    op.drop_column('assets', 'invoice_number')
    op.drop_column('assets', 'purchase_cost')
    op.drop_column('assets', 'purchase_date')
    op.drop_column('asset_categories', 'is_active')
    # ### end Alembic commands ###
